- hosts: elastic
  become: true

  pre_tasks:
    - name: Print Ansible version.
      debug:
        msg: "Installed Ansible Version: {{ ansible_version.full }}"

  roles:
    - deveth0.oracle-java
    - role: ansible-elasticsearch
      es_instance_name: "node1"
      es_java_install: false
      es_heap_size: 1536m
      es_version: "5.2.1"
      es_config: {
        network.host: ["192.168.50.10","localhost"]
      }

